# Site settings
title: Mengjiao's blog
description: 'the blog space of Mengjiao' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mengjiao-liu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "assets/img/branding/mlogo-shadow.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/mlogo.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"
logo-dark: "/assets/img/branding/mlogo-black.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Mengjiao Liu # add your name
author-pic: profile-photo.png
about-author: Kubernetes WG Structured Logging Chair，SIG Instrumentation Reviewer，SIG Docs Chinese Owner，主要涉及的领域为 Kubernetes、Docker 以及 Linux 相关。
# Contact links
email: liumengjiao21@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://mengjiao-liu.github.io # Add your website
#linkedin: mengjiao-liu # Add your Linkedin handle
github: mengjiao-liu # Add your Github handle
twitter: '@Mengjiao99' # Add your Twitter handle
bandcamp: 404 # Add your Bandcamp username
rss: true


# Newsletter
mailchimp: "https://gmail.us5.list-manage.com/subscribe/post?u=9fbb8b48e6b41210766fb9506&id=93100d6d9b"

# Disqus
discus_identifier: mengjiao-liu-github-io # Add your discus identifier
comments_curtain: no # leave empty to show the disqus embed directly

# Tracker
analytics: G-GN6HRLM98R
fbadmin: 1730163964040562

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 80

# Build settings
markdown: kramdown
mathjax: trued
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: ["_pages","baidu_verify_code-RWokSiQito.html"]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]